# This file was generated by GoReleaser. DO NOT EDIT.
cask "orbiflow" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "231734706510ab291969d5b2a3d6d568102ab217b9460f21a35d7aea504d00e8"
      url "https://github.com/arap-korir/orbiflow/releases/download/v#{version}/orbiflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bcbf6df562ff82f83c0ee5777f7523fec044089d9a082c18764e900e5a37b193"
      url "https://github.com/arap-korir/orbiflow/releases/download/v#{version}/orbiflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "00ad9c2eace83108bb15a2f9dd6bc3238d69662cedba2397ec85abcbc5392309"
      url "https://github.com/arap-korir/orbiflow/releases/download/v#{version}/orbiflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4164861426f8dcab744a29c31ec86b75149e862e829c70674071795eb9f7430b"
      url "https://github.com/arap-korir/orbiflow/releases/download/v#{version}/orbiflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "orbiflow"
  desc "Agentic software delivery pipeline for software repos"
  homepage "https://github.com/arap-korir/orbiflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orbiflow"

  # No zap stanza required

end
