# This file was generated by GoReleaser. DO NOT EDIT.
cask "orbiflow" do
  version "0.7.8"

  on_macos do
    on_intel do
      sha256 "e74eb807c5e804afc4559f3a583bb8853547fab057a8a902e39dbb849f478bff"
      url "https://github.com/arap-korir/orbiflow/releases/download/v#{version}/orbiflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3242e0e20379734a2760e4a9dd7f5fba747d8e7c3fa0ad6b0d24f9b63eeca2c5"
      url "https://github.com/arap-korir/orbiflow/releases/download/v#{version}/orbiflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ac431b1095eacd81cae8f857bb6765e3d7e756a007aa63ae2865b607e722b519"
      url "https://github.com/arap-korir/orbiflow/releases/download/v#{version}/orbiflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7580b88ae4b818804b664096aac6068ea9705e90da41b0586bd9fe415d9a93a2"
      url "https://github.com/arap-korir/orbiflow/releases/download/v#{version}/orbiflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "orbiflow"
  desc "Agentic software delivery pipeline for software repos"
  homepage "https://github.com/arap-korir/orbiflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orbiflow"

  # No zap stanza required

end
