# This file was generated by GoReleaser. DO NOT EDIT.
cask "orbiflow" do
  version "0.7.9"

  on_macos do
    on_intel do
      sha256 "3d67d621e5b758e4675e34d68699ddcaf48aff1426e2bfa31c7a2c3fe36b80d2"
      url "https://github.com/arap-korir/orbiflow/releases/download/v#{version}/orbiflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c08ba47b862b7b46950ac701987167dbd56232c5d3c419639637812063131b7b"
      url "https://github.com/arap-korir/orbiflow/releases/download/v#{version}/orbiflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "40f058844dadfdcec46810f8e609e57b935a13ff7c5638c6f95d15e5287b84c2"
      url "https://github.com/arap-korir/orbiflow/releases/download/v#{version}/orbiflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "16b6823412f81c83390ae9e08a2f809b5a0016f27e89a9d7f7a4b6b4e9d8b2a0"
      url "https://github.com/arap-korir/orbiflow/releases/download/v#{version}/orbiflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "orbiflow"
  desc "Agentic software delivery pipeline for software repos"
  homepage "https://github.com/arap-korir/orbiflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orbiflow"

  # No zap stanza required

end
